name: app_usage_tracker
description: app usage tracker
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  installed_apps: ^1.6.0
  fl_chart: ^0.68.0

flutter:
  uses-material-design: true
